version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: savvy-backend
    restart: unless-stopped
    ports:
      - '4000:4000'
    environment:
